### ISSUE TITLE
Getting different results on same image with default configuration

### ISSUE THREAD

**Issue by seme1** [naptha/tesseract.js#107]
I've installed tesseract on my local machine and attempted to OCR an image with the default configurations. The output of the run was perfect. I then attempted to run tesseract.js on the same image and the output was different (it got one character wrong as it recognized the number 7 incorrectly as T). 

What could be the reason for the above ? The version of Tesseract I have running on my machine is the following:
Tesseract Open Source OCR Engine v3.03 with Leptonica

I also attempted to copy the training file eng.traineddata from my local machine (which has Tesseract 3.03 running) and forced tesseract.js to use a compressed version of that same file (through using the tesseract.create() and then specifying a local URL for the lang file). Unfortunately, this did not make a difference and tesseract.js still incorrectly recognizes the number 7 as T in the same image. 

What can I do to resolve the above problem ?

**Comment by bijection** [comment]
Responding here, but I also saw your tweet. I'm not 100% sure why the results are different, but I imagine it's because javascript image decoding is bound to differ slightly from however tesseract decodes images natively. Since it seems the js is doing objectively worse, I'd advise you to try upscaling your image before feeding it in, as that generally improves tesseract's accuracy. Hope that helps!
