### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by brunoschuermans** [naptha/tesseract.js#134]
With version 1.0.10
When using the Simple example of the documentation i got:

Uncaught SyntaxError: Unexpected token <
    at blob:http://localhost:3000/49b8248d-3fa6-4529-a4bc-532adde1c6cc:1
(anonymous) @ blob:http://localhost:3000/49b8248d-3fa6-4529-a4bc-532adde1c6cc:1

**Comment by SidneyNemzer** [comment]
Had the same issue. Solved by switching from NPM version to CDN version.

EG, remove `import Tesseract from 'tesseract.js'`, add a script tag with the latest tesseract version `<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>`

**Comment by CarlosAmaral** [comment]
Can someone shed some light on this? Adding a CDN isn't the best solution

**Comment by adamczykjac** [comment]
Same here, tried using 1.5RC2 version of `uglifyjs-webpack-plugin` as suggested in https://github.com/angular/angular-cli/issues/7756#issuecomment-336452435, but no effect.

**Comment by BrianTatum** [comment]
I am having the same issue in a react app. Anyone get this to work yet?

**Comment by SidneyNemzer** [comment]
Did switching to the CDN not fix it, @BrianTatum? I'm not sure why it seems to have worked only for me...

**Comment by adamczykjac** [comment]
Indeed as @SidneyNemzer suggests, using the version from CDN works, but for TypeScript newcomers it may seem as a no-no, as we'd like to make use of
`import * as Tesseract from 'tesseracts.js'`
in our module after all. To get this working, apart from having
`<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>`
in our `index.html` and removing the above `import ...` line from our module implementation, one needs to have a globally scoped `declare var Tesseract` in a file you declare your types (in my case it's `typings.d.ts`), so TS compilation can go through. To retain having hints in your IDE, just install Tesseract's types with `npm install @types/tesseract.js --save-dev`.

PS Have a double look at how you invoke Tesseract worker methods. In my case, I was missing an obvious `ImageLike` argument there, and I was getting the same error as this issue suggests -.-

**Comment by BrianTatum** [comment]
I am not sure if I am getting the image like file set correctly from some
of the reading that I have done today. Is there a good example of getting
the file set to pass into Tesseract?

On Nov 2, 2017 9:05 AM, "adamczykjac" <notifications@github.com> wrote:

Indeed as @SidneyNemzer <https://github.com/sidneynemzer> suggests, using
the version from CDN works, but for TypeScript newcomers it may seem as a
no-no, as we'd like to make use of
import * as Tesseract from 'tesseracts.js'
in our module after all. To get this working, apart from having
<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/
dist/tesseract.js'></script>
in our index.html and removing the above import ... line from our module
implementation, one needs to have a globally scoped declare var Tesseract
in a file you declare your types (in my case it's typings.d.ts), so TS
compilation can go through. To retain having hints in your IDE, just
install Tesseract's types with npm install @types/tesseract.js --save-dev.

PS Have a double look at how you invoke Tesseract worker methods. In my
case, I was missing an obvious ImageLike argument there, and I was getting
the same error as this issue suggests -.-

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/naptha/tesseract.js/issues/134#issuecomment-341430997>,
or mute the thread

**Comment by adamczykjac** [comment]
@BrianTatum What do you mean exactly by file set? Afaik Dropzone is only another way to provide your API endpoint with some form data, so you'd need to get the location/name of this just uploaded file and pass it to `Tesseract.recognize(yourFilePath)` (as I assume you use it on the server side, which shouldn't matter after all). 

Besides, I guarantee you don't have to import it into your React module to get this working as React itself is a framework added within `<script>` tag, it's just being marshalled/compiled/squeezed along the way once "it get's there", i.e into your HTML document.

In case it's still not clear, get us some code so we can have a look at it and eventually help.

**Comment by Phongtlam** [comment]
I am getting the same error whether using CDN or import module
Here is my basic code

import React from 'react';
var Tesseract = require('tesseract.js')

class Upload extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      image: '',
      imageViewer: '',
    }
  }

  handleSubmit = (e) => {
    e.preventDefault();
    let myImage = this.state.image;
    console.log('in handle submit image', myImage);
    Tesseract.recognize(myImage)
    .progress(message => console.log(message))
    .catch(err => console.error(err))
    .then(result => console.log('result', result))
    .finally(resultOrError => console.log(resultOrError))
  }

  imageChange = (e) => {
    e.preventDefault();
    let reader = new FileReader();
    let image = e.target.files[0];

    reader.onloadend = () => {
      this.setState({
        image,
        imageViewer: reader.result,
      })
    }
    reader.readAsDataURL(image);
  }

  render() {
    let imageViewer = this.state.imageViewer;
    let $imageViewer = null;
    if (imageViewer) {
      $imageViewer = (<img src={imageViewer} />);
    } else {
      $imageViewer = (<div className="previewText">Please select an Image for Preview</div>);
    }
    return (
      <div className="previewComponent">
        <form onSubmit={(e)=>this.handleSubmit(e)}>
          <input className="fileInput"
            type="file"
            onChange={(e)=>this.imageChange(e)} />
          <button className="submitButton"
            type="submit"
            onClick={(e)=>this.handleSubmit(e)}>Upload Image</button>
        </form>
        <div className="imgPreview">
          {$imageViewer}
        </div>
      </div>
    )
  }
}

export default Upload;

**Comment by urakozz** [comment]
Hey typescripters! I did a tiny and nice package solving this issue here: [tesseract.ts](https://github.com/urakozz/tesseract.ts).
Just install it and change import to
```typescript
// npm i -S typescript.ts typescript.js
import {Tesseract} from "tesseract.ts";
```
@brunoschuermans @Phongtlam

**Comment by ichigo92** [comment]
@urakozz thanks for the package, solved this issue.
