### ISSUE TITLE
Using tesseract.js with rhino engine

### ISSUE THREAD

**Issue by malaythecool** [naptha/tesseract.js#169]
Hi,

I want to use tesseract.js with rhino engine but i am not able to figure out as rhino doesn't have the browser Dom and so directly i am not able to use there.
Is there any way by which I am able to use it with rhino?

Thanks,
Malay

**Comment by jeromewu** [comment]
I have done survey and I have to say that we don't plan to support rhino engine due to following reasons:

1. Rhino engine doesn't look like to support asm.js or Webassembly
2. As rhino engine provides capabilities to combine JavaScript and Java, it is more recommend to use JNI and leverage native tesseract-ocr to get better performance
