### ISSUE TITLE
use language offline and version 4.00

### ISSUE THREAD

**Issue by doantutai** [naptha/tesseract.js#231]
I don't know using language offline in tesseract and i want version language 4.00.
Thanks you.

**Comment by valerius21** [comment]
My guess is that this Repository is focused on version 3.02, because it should make use of the Tessdata Repository from this very same Project. 
If you are using node, you can use language offline by specifying a path under the `langPath` property by defining the given operation:

Ex. using the German Language
Let's just say, this image is named `sample.jpg`

![sampleText](https://i.imgur.com/pUB7gpY.jpg)

corresponding example code snippet:

```javascript
// ocr.js
// using code from the examples/basic.js code
var Tesseract = require('tesseract.js'),
    image = require('path').resolve(__dirname, 'sample.jpg'),
    ldata = require('path').resolve(__dirname, 'deu.traineddata'); // using extracted language data in the same directory as the ocr.js is

Tesseract.recognize(image, {
    lang: 'deu', // defining the language which will be used
    langPath: ldata // setting the path for the offline data
    })
    .then(data => {
        console.log('then\n', data.text)
    })
    .catch(err => {
      console.log('catch\n', err);
    })
    .finally(e => {
      console.log('finally\n');
      process.exit();
    });
```

Results in:
```
pre-main prep time: 52 ms
then
 lIlI. g) Nach wie vor spieltdie strafrechtliche
[Behandlung der Polen im Altreich eine erhebliche Rolle.
[Eine Einheitlichkeit des Vorgehens gegen sie besteht

nicht und ist m.E. auch sälange nicht zu erzielen,als
‘nicht‚was zum mindesten für das Altreich dringend geboten
1wäre,sowohl in materiell rechtlicher wie Verfahrensrecht-
!licher Hinsicht klare und einheitliche gesetzliche Grund—
lagen geschaffen und die Befugnisse der Stdpo klar begrenzt,
Ed.h. eingeschränkt sind.juvüwgﬂ 74' 7 iii_„‚„.‘‚ V ‚„

finally
```

**Comment by jeromewu** [comment]
I think @valerius21 already gave a good answer for the first question, for the second question, we are now working on tesseract.js v2 which will use tesseract 4.0.0 as its core.

Please keep patient for our announcement in the future. 😃
