### ISSUE TITLE
npm install tesseract.js --save is not working 

### ISSUE THREAD

**Issue by HasanAliKaraca** [naptha/tesseract.js#248]
yarn command is working but npm install not working on windows 10. It doesn't create anything.
`npm install tesseract.js --save`

![image](https://user-images.githubusercontent.com/2185905/48711305-01e7ad80-ec1c-11e8-8fd0-288c2b5c386a.png)

**Comment by jeromewu** [comment]
This is an interesting scenario, why you don't get node_modules in D:\VSCode\tesseractjs folder is because you have a package.json in D:\VSCode (not D:\VSCode\tesseractjs), so the tesseract.js actually installs in D:\VSCode instead of D:\VSCode\tesseractjs

To solve this issue, please do **npm init** in D:\VSCode\tesseractjs first, and you will install the package to the proper location.

**Comment by HasanAliKaraca** [comment]
Thanks @jeromewu this solved the issue. I updated the readme.

**npm init** must be called first.
