### ISSUE TITLE
Specific language for programming?

### ISSUE THREAD

**Issue by CKGrafico** [naptha/tesseract.js#284]
Do you have plans to support programming as language? If I add an image like this is having some issues.

<img width="552" alt="Screenshot 2019-05-21 at 15 52 46" src="https://user-images.githubusercontent.com/2048511/58102455-976ef480-7be1-11e9-8484-f41433b1cb44.png">

```
import { insights } from './insights';
class CartService {
constructor() {
this.products = [1;
}
add(product) {
this.products.push(product);
insights.info(‘Product ${product.id} added from cart‘);
}
}

```

**Comment by jeromewu** [comment]
One way is to do some preprocessing to the image.
Please check link here: https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by CKGrafico** [comment]
Sorry @jeromewu not sure about that, why preprocessing? my problem here is that `a = [];` is converted to `a = [1;]` I understand that this kind of error is because the 'language understanding' or something like that, isn't it? by the moment what I'm doing is a post process https://github.com/CKGrafico/ScreenshotToCodeSandbox/blob/master/app/scripts/post-processors/empty-array.js

**Comment by jeromewu** [comment]
When it comes to image processing, both preprocessing and postprocessing are common approach to conquer the accuracy issue.
Why I mentioned preprocessing is because that tesseract is not good at image with black background and white text, so I think preprocessing may help. Another approach is to train your own model for the programming language, which will highly raise the accuracy. And for postprocessing like 'language understanding', right now I don't have any plan for that as it is out of the scope of tesseract.js

**Comment by CKGrafico** [comment]
I'm having similar problems in light theme, for example 'function()' converted to 'Function()' and things like that, this is not related with the language? maybe to have a english-programming as language could help.

I think that is not related with the image quality or colors

**Comment by jeromewu** [comment]
Good point, I think the suitable approach might be training your own data or postprocessing.

For training data, check link here: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

**Comment by jeromewu** [comment]
Close this issue for now as the approach is clear.
