### ISSUE TITLE
Does it connect to a server

### ISSUE THREAD

**Issue by pjebs** [naptha/tesseract.js#335]
In package.json dependencies:
```
"dependencies": {
    "axios": "^0.18.0",
    "check-types": "^7.4.0",
    "is-url": "1.2.2",
    "node-fetch": "^2.3.0",
    "opencollective-postinstall": "^2.0.2",
    "resolve-url": "^0.2.1",
    "tesseract.js-core": "^2.0.0-beta.11",
    "tesseract.js-utils": "^1.0.0-beta.8"
  },
```

I can see `axios` and `node-fetch`, Does that imply this library connects to an external server?

**Comment by codeclown** [comment]
`axios` is used in `loadImage`:

https://github.com/naptha/tesseract.js/blob/5dd382a67a88bca399e39d792bce7b237c0e5682/src/node/index.js#L35

`node-fetch` is not used anywhere according to GitHub search.

In addition the dependency `tesseract.js-utils` uses `axios` to download training data archives:

https://github.com/jeromewu/tesseract.js-utils/blob/f2b68f83e7d138a1c472d610ccfbd975026047e4/src/loadLang.js

---

I am researching this because I don't feel good about a third-party library initiating data downloads from a third-party server in the background of this clean JavaScript API. I'd rather utilize the traineddata obtained via downloading tesseract from apm.

**Comment by pjebs** [comment]
How can I remove network dependencies?

**Comment by codeclown** [comment]
I don't think they'll be removed from this package. You could use [tesseract.js-core](https://github.com/naptha/tesseract.js-core/tree/v2.0.0-beta.11), which is what I'm trying to do.

**Comment by jeromewu** [comment]
node-fetch is a leftover and will be removed soon.
May I know your scenario of using tesseract.js? It is hard for me to understand your requirement for now.

**Comment by codeclown** [comment]
My use case is that I want to use Tesseract in node using previously downloaded traineddata-files.

(Even if it is possible using tesseract.js, I think this module does too much for the use case.)

**Comment by jeromewu** [comment]
Got it, it is totally doable to bypass tesseract.js and use tesseract.js-core directly, you can reference the code base to know the details, especially this one: https://github.com/naptha/tesseract.js/blob/master/src/common/workerUtils.js

**Comment by codeclown** [comment]
I made my own wrapper, maybe @pjebs finds it useful as well:
https://github.com/codeclown/tesseract.js-node

**Comment by jeromewu** [comment]
Close for now, feel free to reopen if needed.

**Comment by pjebs** [comment]
@iykekings
