### ISSUE TITLE
Reliability quite inferior to original Tesseract OCR

### ISSUE THREAD

**Issue by diogoscf** [naptha/tesseract.js#435]
The output given by tesseract.js is much less reliable than the one given by the original Tesseract OCR.

For the following image:
![tmep](https://user-images.githubusercontent.com/26374538/78462911-293aff80-76d7-11ea-8c0b-b1e5475496dc.jpg)

Tesseract OCR gives the expected output:

````
[ASMR] Google Pixel 4
Unboxing & Features — soft
spoken, fast tapping

29,353 views - 5 months ago
````

However tesseract.js gives a much more unreliable output:
````
S e Yo e | R C R -
Unboxing & Features — soft
spoken, fast tapping

29,353 views - 5 months ago
````

This is just an example, and the reduced quality of the output can be seen with many other images

**Comment by bartekpacia** [comment]
that's because it mentions ASMR

**Comment by jeromewu** [comment]
From my guess, which may not be totally right.

As tesseract is using neural network which involves tons of numeric operations during the process to produce the OCR result, it is highly possible we will have precision loss during as we transpile the code from C/C++ to WebAssembly, it is not quiet easy to get same precision as the way they handle the numbers may be different. So I think this issue is pretty normal and the solution is unknown for now.

**Comment by CharlieHess** [comment]
> it is highly possible we will have precision loss during as we transpile the code from C/C++ to WebAssembly, it is not quiet easy to get same precision as the way they handle the numbers may be different

this is a pretty wild admission; it should probably be put at the front of the repo in big letters. I think it's a safe assumption for many developers that this lib would get identical or close to identical results. but indeed, after using tesseract.js for a few weeks and running into near constant bogus results, I finally downloaded the prebuilt binary and it snap passes all of them, with no fallbacks or anything else. Insane!!
