### ISSUE TITLE
dataPath does not work

### ISSUE THREAD

**Issue by leo-regov** [naptha/tesseract.js#481]
**Describe the bug**
It could be not a bug but setting the dataPath does not work. Could be the permission level but still setting it to /tmp does not seem to work.

**To Reproduce**
1. Set the dataPath
2. Do a request

**Expected behavior**
Tesseract should be able to write the {lang}.traineddata to the said dataPath.

**Screenshots**
Code used.
![image](https://user-images.githubusercontent.com/66946660/92187133-8526d180-ee8b-11ea-9d0a-bcc3da587476.png)
Error Produced
![image](https://user-images.githubusercontent.com/66946660/92187316-fb2b3880-ee8b-11ea-8ac8-c15cecf20c7a.png)

Console. log in worker-script.index.js
Path
![image](https://user-images.githubusercontent.com/66946660/92187420-4a716900-ee8c-11ea-8819-f9de8b7863f6.png)
Error stack (after putting try-catch in Tesseract.FS.writeFile)
![image](https://user-images.githubusercontent.com/66946660/92187496-85739c80-ee8c-11ea-99df-1b3e6a602b92.png)
Reference for above reproduction
![image](https://user-images.githubusercontent.com/66946660/92187614-d71c2700-ee8c-11ea-9ddf-7c7d4080bf35.png)

Lambda Error (for additional reference, after changing to dataPath: /tmp, langPath: /tesseract/lang)
![image](https://user-images.githubusercontent.com/66946660/92190105-d4bccb80-ee92-11ea-9d03-781af36f4a1a.png)
For stack trace, refer to Error Stack

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Version Tesseract 2.1.1

**Additional context**
I am trying to make Tesseract work in Lambda.
The said error does not even return anything,  just stuck in the generic error stack (local dev).
Image is a base64.
The code works without the dataPath, but like I said, I need it in Lambda and set the dataPath to the tmp directory.
Related error for Lambda is EROFS, read-only filesystem, for error reference in Lambda which I am experiencing.

**Comment by phoenixxd** [comment]
I get a similar error when I execute tesseract.js in google cloud functions

`Error: EROFS: read-only file system, open './eng.traineddata' at ChildProcess.onMessage (/workspace/node_modules/tesseract.js/src/createWorker.js:173:15) at ChildProcess.emit (events.js:198:13) at ChildProcess.EventEmitter.emit (domain.js:448:20) at emit (internal/child_process.js:832:12) at process._tickCallback (internal/process/next_tick.js:63:19)`

Apparently tesseract is trying to open the trainedData with write access as well. Is there any way that we can make it open for reading purpose only. 
Probably it will work then, as GCP cloud functions only allow read-only access to files.

**Comment by phoenixxd** [comment]
I found solution to my problem as follows. Just changing the langPath worked, didnt had to touch the dataPath.

```
const fs = require('fs');
// destination.txt will be created or overwritten by default.
fs.copyFile('./eng.traineddata', '/tmp/eng.traineddata', (err) => {
    if (err) throw err;
    console.log('source.txt was copied to destination.txt');
});

const worker = createWorker({
    // logger: m => console.log(m)
    langPath: 'tmp',
    cacheMethod: 'none',
    gzip: false
});

```
As the file was getting opened with write permissions as well, I did a copy of the file to the temp location before createWorker was called. Now, cloud functions is working as expected :D

**Comment by leo-regov** [comment]
Closing. @phoenixxd thanks for the guide but we already switched to another provider.

**Comment by JounQin** [comment]
I got the problem too, although copy data first will work, but I hope not adding the data file to `git`, so a better solution would be awesome.

**Comment by addshore** [comment]
I finally found this issue after seeing `Ignoring extra callback call` in my logs without an error handler registered while using this library in google cloud functions / firebase.
It would then just `Finished with status: crash` with no other output.

Leaving this comment here so that other folks might find it easier in the case they get the same log message.

I'm copying the "fix" from https://github.com/naptha/tesseract.js/issues/481#issuecomment-705223523 to move the file to tmp

**Comment by mrn3** [comment]
> I found solution to my problem as follows. Just changing the langPath worked, didnt had to touch the dataPath.
> 
> ```
> const fs = require('fs');
> // destination.txt will be created or overwritten by default.
> fs.copyFile('./eng.traineddata', '/tmp/eng.traineddata', (err) => {
>     if (err) throw err;
>     console.log('source.txt was copied to destination.txt');
> });
> 
> const worker = createWorker({
>     // logger: m => console.log(m)
>     langPath: 'tmp',
>     cacheMethod: 'none',
>     gzip: false
> });
> ```
> 
> As the file was getting opened with write permissions as well, I did a copy of the file to the temp location before createWorker was called. Now, cloud functions is working as expected :D
> 
> PS: I included the trained data along with index.js so it is being copied from the same location

Does this still work?  I have tried this on google cloud function, and still getting errors.  I tried with langPath of both 'tmp' and '/tmp', and still getting errors like:

 Error opening data file ./eng.traineddata
>  Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
>  Failed loading language 'eng'
>  Tesseract couldn't load any languages!

**Comment by Yahya-khodr** [comment]
How to place this TESSDATA_PREFIX ? Should I add the whole tessdata directory to my project ? because I only have 1 file eng.traineddata but I have the error when I call google cloud function.

Here is the error 

 [Error: ENOENT: no such file or directory, copyfile 'project_path\functions\eng.traineddata' -> 'C:\tmp\eng.traineddata'] {
>    errno: -4058,
>    code: 'ENOENT',
>    syscall: 'copyfile',
>    path: 'project_path\\functions\\eng.traineddata',
>    dest: 'C:\\tmp\\eng.traineddata'
>  }

**Comment by addshore** [comment]
> Does this still work? I have tried this on google cloud function, and still getting errors. I tried with langPath of both 'tmp' and '/tmp', and still getting errors like:

> Error opening data file ./eng.traineddata

Yes this was working for me in the past weeks, but you need to send the `eng.traineddata` with your function

Specifically, take a look at https://github.com/addshore/yt-scam-hunter/blob/392329b15e0ddfce77bcc40f2f400feda37381a3/functions/src/tesseract.js#L25-L55 for working code

And to make fetching the file easier, I added a step to my deploy command
https://github.com/addshore/yt-scam-hunter/blob/a504b189e33cb64b93ef23eff24f1b04a89b6d38/functions/package.json#L10
Which would force the data to be downloaded, so that it would also be sent to the cloud with the function https://github.com/addshore/yt-scam-hunter/blob/a504b189e33cb64b93ef23eff24f1b04a89b6d38/functions/build/fetchTesseract.js

**Comment by Yahya-khodr** [comment]
@addshore  my folder structure is 
functions/
  modules/imagetoText.ts
  index.ts.
  I've added eng.traineddata the same as index.ts, but still can't copy the file and even read it
