### ISSUE TITLE
GetPDF() with Scheduler returns the same PDF file

### ISSUE THREAD

**Issue by saxelsen** [naptha/tesseract.js#488]
First of all, great work with this project! It's an impressive feat so far, despite the performance difference between this and native Tesseract.

**Describe the bug**
When using a Scheduler with multiple Workers, creating a `GetPDF()` job returns the same PDF document repeatedly, even though the Scheduler processes multiple different files.

**To Reproduce**

```
const {createWorker, createScheduler} = require('tesseract.js');
const fs = require('fs');

const scheduler = createScheduler();
const nWorkers = 4;

async function initialize() {
    for (let i = 0; i < nWorkers; i++) {
        let worker = createWorker({
            cachePath: 'langs',
            langPath: 'langs',
            logger: m => console.log(m)
        });
        await worker.load();
        await worker.loadLanguage('dan-fast');
        await worker.initialize('dan-fast');
        scheduler.addWorker(worker);
    }
    console.log('OCR initialized');
}

async function recognize(imagePath) {
    const filePath = imagePath.split('/').slice(-1).pop();
    const result = await scheduler.addJob('recognize', imagePath);
    const {data} = await scheduler.addJob('getPDF', filePath);
    fs.writeFileSync(`images/ocr-${filePath.replace('.png', '.pdf')}`, Buffer.from(data));
    return result.data.text
}

initialize()
    .then(() => {
        const promises = [];
        for (let i = 0; i < 3; i++) {
            const promise = recognize(`images/page-${i+1}.png`)
            promises.push(promise);
        }

        return Promise.all(promises)
    })
    .then((results) => {
        results.forEach((res) => {
            console.log('-----------');
            console.log(res);
        })
    })
    .then(() => {
        return scheduler.terminate();
    });
```

**Expected behavior**
`GetPDF()` should be able to produce the PDF file (or its byte representation) associated with a given recognition job, or the PDF byte representation should be part of the result from the recognition job.

The current operating model disables OCR-PDF rendering when using a scheduler, making processing a document with several pages more time-consuming.

**Screenshots**
![Screen Shot 2020-10-07 at 14 48 30](https://user-images.githubusercontent.com/3410995/95332826-3b773f80-08ac-11eb-8bbc-57e6126ea2f5.png)

**Versions:**
 - OS: Mac OS 10.13.6
 - Node: v12.18.1
 - Tesseract.js: 2.1.3

**Comment by Balearica** [comment]
Thanks for reporting.  I think the issue is inherent to `getPDF` being its own function, and agree with your second proposed solution ("the PDF byte representation should be part of the result from the recognition job.").

In general, using a scheduler assumes that all workers are fungible, so any job can be sent to any worker.  This makes sense for `detect` and `recognize`, but not other functions.  E.g. if you used `loadLanguage` through a scheduler, it would just set the language of a random worker.  I think this limitation is fine in the case of `loadLanguage`, but it clearly does not make sense for `getPDF`.  

As `getPDF` is currently the only output format that requires a separate function call (we don't have separate functions for getting the raw text, hocr, etc.), I think the most intuitive and straightforward solution is to depreciate that function and add an option for `recognize` to return a PDF.

**Comment by Balearica** [comment]
I added a recognition option called `savePDF` which when set to `true` will include the PDF in the results on the [dev/v4 branch](https://github.com/naptha/tesseract.js/tree/dev/v4) branch, and will be included with the next major release (v4).  I also updated both the PDF examples for both [browser ](https://github.com/naptha/tesseract.js/blob/dev/v4/examples/browser/download-pdf.html) and [node ](https://github.com/naptha/tesseract.js/blob/dev/v4/examples/node/download-pdf.js) in that branch.  

To learn more about changes in v4 and/or try out the changes see Issue https://github.com/naptha/tesseract.js/issues/662.

**Comment by saxelsen** [comment]
Great, thanks a lot for spending time on it! I'll mark this issue as closed and migrate my current solution over once v4 is released :)
