### ISSUE TITLE
I don't get any output on specific images

### ISSUE THREAD

**Issue by 1Euro7Cent** [naptha/tesseract.js#531]
**Describe the bug**
an image like this doesn't give me anything except if I replace more underscores with letters
![Screenshot2](https://user-images.githubusercontent.com/67194495/113836902-96bbb900-978d-11eb-99b2-29ebfd69c06d.png) 

**To Reproduce**
1. Use the given image
2. throw it in the recognizer
3. see that it doesn't give anything

**Expected behavior**
something like this `___l_ _____`

**Screenshots**

![image](https://user-images.githubusercontent.com/67194495/113837396-177ab500-978e-11eb-94b8-b216f015dd80.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64 bit]
 - Browser [just NodeJS v14.16.0] (no browser)
 - Version [tesseract.js: ^2.1.4]

**Comment by Balearica** [comment]
It sounds like tesseract.js is performing as expected, however you find the Tesseract recognition engine's results unsatisfactory. 

This repository is just for the webassembly port of Tesseract.  We don’t make any edits to the Tesseract recognition engine.  Therefore, when encountering recognition issues you should check whether the results are similar using the CLI version of Tesseract (with the same version/settings).  If they are, then the issue is outside of the scope of this project and should be directed to the main [Tesseract project](https://github.com/tesseract-ocr/tesseract).
