### ISSUE TITLE
OCR doesn't work on this image

### ISSUE THREAD

**Issue by MuhammedAlmaz** [naptha/tesseract.js#547]
I don't know why but the OCR doesn't work on this image.
Can someone explain me why doesn't work on it?

![image](https://user-images.githubusercontent.com/17336091/122350101-942bcb80-cf55-11eb-9dd5-909739223dbf.png)

================RESULT============
{Lv50] Carcs (Killed)
e
e
T
e
ey
e
e s
(e e
o el
P Sy
ettt
e
e

**Comment by albirrkarim** [comment]
I think you must do a preprocessing image like otsu,etc before doing OCR

**Comment by Balearica** [comment]
This repository is for the webassembly port of Tesseract.  We don’t make any edits to the Tesseract recognition engine.  Therefore, when encountering recognition issues you should check whether the results are similar using the CLI version of Tesseract (with the same version/settings).  If they are, then the issue is outside of the scope of this project and should be directed to the main [Tesseract project](https://github.com/tesseract-ocr/tesseract).
