### ISSUE TITLE
Support for WebP Image Format

### ISSUE THREAD

**Issue by hvg2416** [naptha/tesseract.js#548]
**Is your feature request related to a problem? Please describe.**
Yes, I was exploring the tesseract.js then I got errors while trying to run OCR on webp images

**Describe the solution you'd like**
I hope tesseract.js community will soon add support for the webP image format as it is one of most used image formats for the web.

**Describe alternatives you've considered**
As an alternative, we can take help of image convertors to convert our webP images to jpeg or png & then we can run OCR on them.

**Additional context**
I am sharing the console screenshot showing tesseract worker's logs below:

<img width="1436" alt="Error Screenshot" src="https://user-images.githubusercontent.com/49445823/122435404-99206780-cfb5-11eb-82ff-b705e8667d5d.png">

Image URL on which I tried to run OCR is https://upload.wikimedia.org/wikipedia/commons/0/0f/Digital_marketing_1.webp

**Comment by Balearica** [comment]
@hvg2416 Your link is broken, however I created a sample image in .webp and it was recognized correctly in both browser and node.  So perhaps this was resolved by a recent update.  If this issue is still active, please confirm whether your .webp images work using the current master branch.  Regardless, we should add a .webp image to the set of tests.

**Comment by hvg2416** [comment]
Yes. I also checked today & it's working for .webp images now.

**Comment by Balearica** [comment]
Great, closing issue then.
