### ISSUE TITLE
invalid code length createWorker 

### ISSUE THREAD

**Issue by ahmedmesawer** [naptha/tesseract.js#551]
createWorker.js:163 Uncaught Error: Error: invalid code length: 6
    at createWorker.js:163
    at Worker.worker.onmessage (onMessage.js:6)
(anonymous) @ createWorker.js:163
worker.onmessage @ onMessage.js:6
App.js:16 Uncaught (in promise) Error: invalid code length: 6

trying to execute the ocr example in react app

**Comment by Balearica** [comment]
If this issue is still active, please confirm if you mean this happens our React sample ([this repo](https://github.com/jeromewu/tesseract.js-react-app)) or that this happened when you added some example code to your own React application.  If the latter is true, please provide a reproducible example that we can clone and run.

**Comment by Balearica** [comment]
Closing as stale.
