### ISSUE TITLE
LSTM requested, but not present trying to load equ trained data

### ISSUE THREAD

**Issue by shadowofsoul** [naptha/tesseract.js#569]
**Describe the bug**
Tesseract.js doesn't load equ trained data, from cache, remote repo or local installation.

**To Reproduce**
```
      await worker.load();
      await worker.loadLanguage('eng+equ');
      await worker.initialize('eng+equ', OEM.LSTM_ONLY);
      await worker.setParameters({
        tessedit_pageseg_mode: PSM.SINGLE_BLOCK,
      });
      const result = await worker.recognize(img);

```

**Expected behavior**
Load equ and eng trained data

**Desktop (please complete the following information):**
 - Tesseract.js 2.1.5

**Additional context**
It has been tested as equ alone, combined etc.., trying to load from remote repo (https://tessdata.projectnaptha.com/4.0.0) and local installation with no success (paths are correct and filename is equ.traineddata.gz, tested with local installation of eng alone and it works). 

Any clues of what i could do to fix it or to provide more info to debug this (the message doesn't really help)?

Thanks.

**Comment by Balearica** [comment]
I investigated this, and it looks like it is a behavior we inherit from Tesseract (rather than anything in this repo).  

1. I tried using the `equ` training data with equivalent settings on the desktop version, and it did not work either.  
2. Looking at the [tessdata repo](https://github.com/tesseract-ocr/tessdata), it claims "The LSTM models (--oem 1) in these files have been updated to the integerized versions of [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) on GitHub".  However, there is no `equ` file in that repo.
3. There are issues in the main Tesseract project reporting [similar errors](https://github.com/tesseract-ocr/tesseract/issues/3693)

As issues inherent to the Tesseract engine and default data are outside the scope of this repo, I don't think there's much actionable here past perhaps removing any misleading references to `equ` being supported (e.g. [here](https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/examples/browser/demo.html#L74)).

**Comment by Balearica** [comment]
Closing as I removed the only reference to `equ` support from this repo, and I don't think there's anything else actionable.

**Comment by Pierre918** [comment]
Hello, I also have an issue with equ.traineddata. 
I am on windows 10 64bit with tesseract 5.3.0
In fact when i only write :
`tesseract Capture1.png nom_du_fichier_de_sortie1 -l fra --oem 1` it works. 

But if i try to write : 
`tesseract Capture1.png nom_du_fichier_de_sortie1 -l fra+equ --oem 1` 
It gives me the following error : 
`Error: LSTM requested, but not present!! Loading tesseract.`

So i think the problem comes from my equ.traineddata.
I have been downloading multiple different equ.traineddata (from tessdata_best, tessdata_fast and tessdata) but none of them work.
Do you have any ideas of where could the problem come from ?
Thank you

**Comment by amitdo** [comment]
Never add `equ` to the `l` flag.

https://github.com/tesseract-ocr/tesseract/issues/3693

**Comment by amitdo** [comment]
@Balearica,

An update: 
The equ.traineddata was just added to the best repo.

**Comment by MarcoHidalgo** [comment]
Having this issue too, but in fact. My code its working properly:
`
   const workers = await Promise.all(
        Array.from({ length: NUM_WORKERS }, async () => {
            const worker = await Tesseract.createWorker();
            
            //await worker.loadLanguage('eng+osd') // 
            await worker.reinitialize('eng+osd');
            await worker.setParameters({
                tessedit_pageseg_mode: Tesseract.PSM.AUTO_OSD 
            });
            return worker;
        })
    );

    const tasks = images.map((image, index) => {
        const worker = workers[index % NUM_WORKERS]; 
        return worker.recognize(`${outputDir}/${image}`)
            .then(({ data: { text } }) => text
                .split(/\s+/)
                .map(word => word.trim())
                .filter(word => word.length > 0)
            );
    });
`
Then it returned me the correct content, but im worried the problem get worse in the future or something. The console shows this:
Error: LSTM requested, but not present!! Loading tesseract.
Error: LSTM requested, but not present!! Loading tesseract.
Error: LSTM requested, but not present!! Loading tesseract.
Error: LSTM requested, but not present!! Loading tesseract.
Estimating resolution as 135
Estimating resolution as 128
OSD: Weak margin (3.17) for 1637 blob text block, but using orientation anyway: 1

**Comment by amitdo** [comment]
Just don't add `+osd`. That is a wrong usages pf Tesseract.

R

**Comment by Balearica** [comment]
Agree with @amitdo that `+osd` likely should not be used here.

@MarcoHidalgo The message being printed is completely literal.  By default Tesseract.js loads the newer LSTM model.  However, the `osd` data does does not contain any LSTM data.  Therefore, requesting LSTM data that does not exist produces a message stating as much: `LSTM requested, but not present`.
