### ISSUE TITLE
Incorrect Worker.terminate interface

### ISSUE THREAD

**Issue by oleg-andreyev** [naptha/tesseract.js#586]
**Describe the bug**
Based on documentation and index.d.ts Worker.terminate can accept JobId (I assume to kill a specific job)
But it looks like that Worker.terminate does not terminate Job itself but entire worker.

**Expected behavior**
- Able to terminate worker by JobId, or even better cancel specific job

**Comment by daniele-orlando** [comment]
I can replicate the bug with tesseract.js `2.1.5`.

From the source code

https://github.com/naptha/tesseract.js/blob/adcb5b875986ebe61d7235e64d956d648c53c1dd/src/createWorker.js#L142-L154

the jobId is not handled.

**Comment by Balearica** [comment]
To clarify what `jobId` is--whenever workers are assigned a "job" (e.g. load, recognize, detect, terminate, etc.) a `jobId` argument is also passed to uniquely identify that job.  Therefore, the `jobId` argument you're looking at refers to the `jobId` of the *termination*, rather than any recognition job that was run earlier. 

I do not believe that it is possible to interrupt a specific recognition job from the outside (from the main thread) without killing the worker.  Identifying a worker to kill based on an earlier `jobId` likely is possible, although I would want to better understand the use case for this before working on anything.

**Comment by Balearica** [comment]
Closing given the reasons above.  Feel free to reopen if the phenomenon of runaway jobs re-emerges in the latest version (v3 or later).
