### ISSUE TITLE
Support for setting tessedit_do_invert

### ISSUE THREAD

**Issue by aaronsgiles** [naptha/tesseract.js#594]
In looking around at ways to improve recognition speed in Tesseract, I see a number of people suggesting that setting `tessedit_do_invert=0` makes a notable difference. However, I don't see `tessedit_do_invert` among the list of parameters that can be set in tesseract.js. Can this be exposed so that we can control it?

In general, the docs heavily imply that only the parameters listed in the docs are supported, so I'm presuming that doing
```
await cacheEntry.worker.setParameters({ tessedit_do_invert:0 })
```
is not sufficient without adding explicit support. At least, I didn't notice any particular difference when doing so.

**Comment by Balearica** [comment]
The vast majority of options usable on the desktop version of Tesseract can be used in Tesseract.js.  You'll want to pass them as strings though--e.g. `tessedit_do_invert:"0"`.  Out of curiosity I ran both Tesseract desktop and Tesseract.js on a scanned document with/without the  `tessedit_do_invert` option and found it produced no noticeable performance difference with either.  Therefore, if you are having issues with performance there is lower hanging fruit.

**Comment by Balearica** [comment]
Closing this issue as, in addition to what is written above, the `tessedit_do_invert` option has been depreciated in the latest version of Tesseract.  Regarding performance overall, the next release of Tesseract.js will run *significantly* faster due to other changes (documented in the benchmark described in #628).

https://github.com/tesseract-ocr/tesseract/blob/5ad5325a0aa8effc47ca033625b6a51682f82767/ChangeLog#L17-L18
