### ISSUE TITLE
Older Version of File-type library is used, which is causing EOL vulnerability 

### ISSUE THREAD

**Issue by anshulgupta8392** [naptha/tesseract.js#711]
**Describe the bug**
Older Version of File-type library is used

I am using the latest version of file-type in my project which is hampering the execution of tesseract createWorker function.
<img width="1268" alt="Screen Shot 2023-01-27 at 11 31 13 PM" src="https://user-images.githubusercontent.com/112496872/215160748-b19547f8-e674-4db2-b6f8-8e6949af77d4.png">

**Comment by OleksiiHryhorian** [comment]
Faced the issue as well.
I have a SNYK test for all added packages to my solution and snyk report shows the tesseract.js includes outdated and vulnerable library **file-type 12.4.2**:
![image](https://user-images.githubusercontent.com/12295728/221804487-43621979-7259-41a4-8415-bf3f46730f6b.png)

![image](https://user-images.githubusercontent.com/12295728/221804051-6da6928c-333b-4393-8e8f-5d6e309dffc9.png)

Would it be possible to resolve this issue please?

**Comment by mtica** [comment]
+1

**Comment by OleksiiHryhorian** [comment]
Adding the link to the comment from Closed thread as it's connected and issue wasn't solved so far:
https://github.com/naptha/tesseract.js/issues/679#issuecomment-1362865108

**Comment by Balearica** [comment]
Would be ideal if a user impacted by this issue could contribute a PR.  I will not have time to develop Tesseract.js in the near future.

**Comment by Balearica** [comment]
I looked into this tonight, and this dependency is quite the headache--I am leaning towards cutting altogether.  

1. The latest versions (>=17) are ESM only, so will not work with our build.  
2. The bug is also patched in [v16.5.4](https://github.com/sindresorhus/file-type/releases/tag/v16.5.4), however that version has separate exports for the Node.js and browser versions, so would require workarounds to run in Tesseract.js (which requires both).  
3. When I got a browser-only version running with v16.5.4, I found this update over *doubled the size* of our worker code, which I do not consider an acceptable tradeoff
  a. `worker.min.js` went from 145.1kB to 297.0kB [+105%]

Rather than work on this further, I think I am going to cut this dependency in the next version.  We currently use `file-type` to (1) detect whether a buffer contains a `.gz` file and (2) detect whether a buffer contains a `.bmp` file.  Figuring out how to do those things from scratch is almost certainly easier than continuing to fiddle with this dependency.

**Comment by Balearica** [comment]
This dependency has been removed in the master branch in #775 for the reasons stated above.  This change will be reflected in the next npm release, which will be version `4.1.0`.

**Comment by Balearica** [comment]
This dependency was removed in the [v4.1.0](https://github.com/naptha/tesseract.js/releases/tag/v4.1.0) release.

**Comment by anshulgupta8392** [comment]
Thanks a lot Balearic
