### ISSUE TITLE
Uncaught Error: initialization failed

### ISSUE THREAD

**Issue by Ashionnal** [naptha/tesseract.js#714]
When I set the language to 'chi_sim', an error is reported when running to initialize, and my language library data has been downloaded. But when I set it to 'eng', the program can recognize it normally
The picture below is the picture set as chi_sim error report
![error](https://user-images.githubusercontent.com/23193694/219571507-df89d40f-61a6-4011-9bcb-f71487a12b80.png)
The picture below is the picture that is set to eng to run smoothly
![normal](https://user-images.githubusercontent.com/23193694/219571794-910952b6-b3a2-4624-80d9-1353ef2112cf.png)

Program Language: React
tesseract.js Version:  4.0.2
chi_sim.traneddata.gz version: 4.0

My Project Git Path:
git@github.com:Ashionnal/tessractjs_demo.git

**Comment by Balearica** [comment]
Your file path is incorrect.  If you copy the `lang-data` folder into `public`, run `npm start` from the root folder, and then visit `http://localhost:3000/` (or whatever the equivalent is on your system) it runs as expected. 

Your perception that the issue only occurred for `chi_sim` but not `eng` is probably because valid English data was already cached on your system and therefore was not being downloaded from `langPath` to begin with.  As these files can be very large, they are cached to avoid downloading every time.  

For debugging purposes, you can clear your saved data by selecting `Inspect Element -> Application Tab-> Storage Tab-> Clear site data`.  Alternatively, you can set `cacheMethod` to "none" when [creating the worker](https://github.com/naptha/tesseract.js/blob/f46cd6cbf706ed9dd2428f0be94301df2ad0c81c/docs/api.md#createworkeroptions-worker). 

That being said, I think the lack of a clear error message saying your path is invalid is an issue, so will open a separate issue to track that.

**Comment by Balearica** [comment]
I looked into why there was not a clear error message, and the issue appears specific to your server configuration.  For whatever reason, on your site the path being fetched can be invalid and the server response code will still be `200` (`ok`).  Therefore, no error is thrown at this line: 

https://github.com/naptha/tesseract.js/blob/v4.0.3/src/worker-script/index.js#L108

I confirmed that our example code will thrown an error at the `worker.loadLanguage` step if the `langPath` is incorrect.
