### ISSUE TITLE
OCR by chi_tra_vert or chi_sim_vert returns garbled results

### ISSUE THREAD

**Issue by chiehan1** [naptha/tesseract.js#730]
**Describe the bug**
OCR by chi_tra_vert or chi_sim_vert returns garbled results

**To Reproduce**
My code is here.

const { createWorker } = require('tesseract.js');

const main = async () => {
  const worker = await createWorker();

  await worker.loadLanguage('chi_tra_vert');
  await worker.initialize('chi_tra_vert');
  const { data: { text } } = await worker.recognize('./vert2.png');
  console.log(text);
  await worker.terminate();
};

**Expected behavior**
The results should be "直書文字\n光學辨識測試\n測試結果都是不正確的字" for the following image
<img width="122" alt="vert2" src="https://user-images.githubusercontent.com/13195099/230857611-85a0d835-cfef-42b4-bdc7-4c4f80dbc3eb.png">

**Screenshots**
![截圖 2023-04-10 下午4 05 14](https://user-images.githubusercontent.com/13195099/230857171-01ffe09b-881b-47f5-bb79-e6949c8eb9aa.png)

**Desktop (please complete the following information):**
 MacOS 13.2.1
"tesseract.js": "4.0.3"
 node.js 18.15.0

**Comment by Balearica** [comment]
Tesseract.js is the Javascript/Webassembly port of Tesseract.  It is unclear whether the issue you describe is an issue specific to Tesseract.js or if this is an issue with the Tesseract OCR engine in general.  Please try recognizing your file (with equivalent settings) using version 5.3.0 of the [main (CLI) Tesseract program](https://tesseract-ocr.github.io/) and confirm whether or not that produces acceptable results.

**Comment by Balearica** [comment]
Closing for now.  Let me know if you investigate further and find that this is a bug unique to Tesseract.js (and not Tesseract) and we can reopen.

**Comment by chiehan1** [comment]
@Balearica 
Thank you for reply.

I found the OCR results of tesseract.js is not the same with Tesseract OCR.

When I use tesseract.js, version 4.0.5
with the following code

```
const { createWorker } = require('tesseract.js');

async function ocr() {
  const worker = await createWorker();
  await worker.loadLanguage('chi_tra_vert');
  await worker.initialize('chi_tra_vert');
  await worker.setParameters({ preserve_interword_spaces: '1' });
  const { data: { text } } = await worker.recognize(imagePath);
  await worker.terminate();

  return text;
}

ocr();
```

the returned string is

```
汐光自
中山員
誰冉光
汀六卻
次光
佃下
為

全

記

富

人
```

I try to install Tesseract OCR with version 5.3.0 as you say.
And I copy the "chi_tra_vert.traineddata" downloaded by tesseract.js directly for the Tesseract OCR, so the traineddata is the same one.

The command is ```tesseract imagePath outputPath -l chi_tra_vert -c preserve_interword_spaces=1```

The result is
```
直書文字
光學辦識測起
測武結果都是不正雁的字
```

The testing image is
<img width="122" alt="vert2" src="https://github.com/naptha/tesseract.js/assets/13195099/d682602e-a75e-4ed0-83fe-21a6590f98f5">

**Comment by Balearica** [comment]
Thanks for following up on this, I've re-opened the issue.  I replicated your results using the Tesseract CLI, however also replicated the Tesseract.js results using the Tesseract API (code below).  Tesseract.js (and any other programs that use Tesseract) make use of the API.  

Therefore, it looks like the difference in results is due to a difference between the Tesseract CLI vs. API rather than Tesseract.js vs. Tesseract.  I'm guessing that the Tesseract CLI sets some default settings that the API does not, but am not immediately sure what the difference is.  

```
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>

int main()
{
    char *outText;

    tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
    if (api->Init(NULL, "chi_tra_vert")) {
        fprintf(stderr, "Could not initialize tesseract.\n");
        exit(1);
    }

    // Open input image with leptonica library
    Pix *image = pixRead("chi_example.png");
    api->SetImage(image);
    // Get OCR result
    outText = api->GetUTF8Text();
    printf("OCR output:\n%s", outText);

    // Destroy used object and release memory
    api->End();
    delete api;
    delete [] outText;
    pixDestroy(&image);

    return 0;
}
```

**Comment by Balearica** [comment]
@chiehan1 It turns out that the Tesseract API has a different default page segmentation mode than the Tesseract CLI.  Editing the page segmentation mode in the Tesseract API (or Tesseract.js) to match the default of the Tesseract CLI resolves this issue. 

For your example, edit your `worker.setParameters` to the following:

```
await worker.setParameters({"tessedit_pageseg_mode": "3", preserve_interword_spaces: '1'})
```

We should probably change the default PSM value of Tesseract.js in some future version.  We should not be using a PSM default that produces gibberish for certain languages, and my guess is that most users of desktop Tesseract are familiar with the CLI rather than the API.

**Comment by chiehan1** [comment]
@Balearica Thank you!! Now it works by changing the PSM value! Thanks a lot!!

**Comment by Balearica** [comment]
Great, closing as completed.
