### ISSUE TITLE
Result is not working fine 

### ISSUE THREAD

**Issue by samprogrammer1** [naptha/tesseract.js#733]
when i choose low quality image and my output of show different like this 

Q A = g 1 ' 7 —CJ’::E
- = r R s A
sz ;2 Sy N JEF-E ‘
N m 33 & e i 3
~ m :‘7}7!' SR L. 1 | e
2 = ,-e oy |
o A : e = ] i
S % ’? 2 |
@ x . - : 1
= - {81 f s 1 g . i |
33 EREEEREIE - 8 | |
= - = %‘ Zim il = ;E‘ 5 —
o A i i B Wi s 3 } . !
= A N Gle 3; ;!\Egﬁ i 5 3 = :
N A IS 85 8583 Sl 5 B |w / £
~N A IS gl= gid gé—zi"g‘ 2 3 s 7
o A & 32 iin ?-?EEE = 3 ; 1? = fe10KiE =
S 2 SyFsEAER] |4 -~ 3
AA CEcaEg | | Si
A A al 82 g | SO | -
A2 LBy =8 | e o
22 R opE | R '*
AR | i | |2 i
n A fa 8 i @ o b 7’1 . 7
| ik A |0 & = A | © ilH T
A A 53 : > - ;
A A EaNaR ST |
| 22 80 01 aq
/ -2 i o o] D & | :
- N Bl I ?.;f N Ei 5 :
L - % .'%; ; 1 o g 3§ UG A 36 YB R This passport contains 36 pages. 3
L T e — il
;!_ - -« i .I.:ﬂ. e :
. “ ) [
1 .. .l. l: ]
: L g - o = } L . k
. : - i rl_.‘ - s '_ S
i = g " N e d - 2 :"; o ol - .;'I:q- I-. v
) : N . o 0 S
“a R s S i ‘ I} . ar
- B . oA - gt -
- T - L e a . T
: - R b i J 'I.:-'_
‘ i R,
. :I.'!F.l
i - L
-

**Comment by Balearica** [comment]
Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues inherited from the Tesseract engine are outside of the scope of this project.  

If you would like to pursue further, you should check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract).  If you encounter a situation where Tesseract CLI recognizes the image correctly but Tesseract.js does not then feel free post it here and we can re-open the issue.  If neither Tesseract CLI or Tesseract.js recognizes your image acceptably, then the issue is due to a bug in Tesseract and is outside the scope of this project.
