### ISSUE TITLE
Extra spaces in non space-delimited language like CJK

### ISSUE THREAD

**Issue by xxchan** [naptha/tesseract.js#748]
**Describe the bug**

Using `tesseract 5.3.1` on the command line with default options don't have this issue, but `tesseract.js` has spaces between characters.

P.S. This is duplicated with https://github.com/naptha/tesseract.js/issues/413, but I'm not sure whether it's fixable now as upstream `tesseract` works out of the box.

**Comment by Balearica** [comment]
I do not believe the solution to this issue changed following #413.  This appears to be fixed by setting `preserve_interword_spaces` to `1`. 

It does not look like the Tesseract recognition engine itself was ever modified to resolve this issue (if it was it would be reflected here).  Rather, it looks like they just changed the default configuration arguments used when you run the command line program with their .traineddata files.  While it may be appropriate for us to look into changing default settings similarly, there does not appear to be anything stopping users from fixing in their projects by changing the configuration settings.

**Comment by xxchan** [comment]
I tried `preserve_interword_spaces`, but unfortunately it doesn't work.

**Comment by xxchan** [comment]
Hmmm, after I set output to `{ text: true }`, it works. Quite weird. Anyway thanks for you quick answer!

**Comment by Balearica** [comment]
`text: true` is the default, so if setting that argument actually impacted the results that would be a bug.  Please post a reproducible example if that is the case.
