### ISSUE TITLE
Incorrect recognition

### ISSUE THREAD

**Issue by azurenekowo** [naptha/tesseract.js#795]
**Tesseract.js version: 4.1.1**

**Describe the bug**.
It incorrectly recognized 1-2 characters or more off from the original input

**To Reproduce**
```js
const Tesseract = require('tesseract.js')
const ocr = await Tesseract.recognize('input.png', 'eng')
console.log(ocr.data.text.trim())
```
<details>
<summary>Samples</summary>

Returns `s99z`
![captcha-white](https://github.com/naptha/tesseract.js/assets/67498765/38ff0726-9351-4cfd-9e97-361674ab6004)

Returns `ccc7m`  
![captcha-white](https://github.com/naptha/tesseract.js/assets/67498765/cb42373e-9444-4800-ba4e-fbfe7b72c3b2)  

Returns `dvvvv31`  
![captcha-white](https://github.com/naptha/tesseract.js/assets/67498765/6e6de470-80da-434d-89bd-373f32841a86)
</details>

**Expected behavior**
It should have recognized those images correctly

**Device Version:**
 - OS + Version: Windows 10
 - Env: Node.JS 18.16.0

**Additional context**
N/A

**Comment by Balearica** [comment]
You could try using the legacy model and see if that yields better results (setting [oem](https://github.com/naptha/tesseract.js/blob/master/docs/api.md#workerinitializelangs-oem-jobid-promise) to `0`).  Tesseract includes two qualitatively different models ("LSTM" [the default] and "Legacy"), and depending on the application one can perform better than the other. 

With regards to recognition accuracy in general, Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  If you would like to pursue further, you should (1) check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) and (2) if so, and you believe this constitutes a bug, raise the issue with that project.

**Comment by azurenekowo** [comment]
Worked, thanks!
