### ISSUE TITLE
cannot parse text when the text is bordered

### ISSUE THREAD

**Issue by roelnano** [naptha/tesseract.js#802]
This not parse
![image](https://github.com/naptha/tesseract.js/assets/138543405/b49b2a0f-afd8-46b6-ae18-49d9f730c0af)

This  parse ok
![image](https://github.com/naptha/tesseract.js/assets/138543405/8c3d828a-39a8-48df-b242-966f06552fb9)

**Comment by Balearica** [comment]
Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  If you would like to pursue further, you should (1) check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) and (2) if so, and you believe this constitutes a bug, raise the issue with that project.
