### ISSUE TITLE
I can't run it on iPhone Safari： Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 3: can't get Function local's type in group 0, in function at index 583)

### ISSUE THREAD

**Issue by JunTsai** [naptha/tesseract.js#823]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
4.1.1-4.1.2
![image](https://github.com/naptha/tesseract.js/assets/21222388/1b2a30d8-9ff9-4fcc-98cd-036a6a6c6f2d)
**Describe the bug**
in the mobile safari throw error:
[Error] Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 3: can't get Function local's type in group 0, in function at index 583). Build with -sASSERTIONS for more info.
 promiseEmptyOnRejected (tesseract-core-simd.wasm.js:1:4284) promiseReactionJob

**Device Version:**
iphone x. iphone xr, iphone 12 safari
node v16.17.6

**Comment by JunTsai** [comment]
corePath:  `${tessPath}/tesseract-core.wasm.js`, i replace it, and it work

**Comment by Balearica** [comment]
@JunTsai That solution will work but is not recommended.  This error should be resolved by setting `corePath` to a **directory** that contains both `tesseract-core.wasm.js` and `tesseract-core-simd.wasm.js`.  Tesseract.js will automatically detect which file to use.  In your case, it should be set to `tessPath` (and you should be sure both files exist in that directory). 

The SIMD-enabled build (`tesseract-core-simd.wasm.js`) is **many times** faster, however is not supported on all devices, so certain device/browser combinations (including all iOS devices) cannot run it.  The version without SIMD support (`tesseract-core.wasm.js`) is much slower, however is supported on all devices.  Therefore, if you set `corePath` to a single file rather than a directory containing both, your application will either be slower than necessary or will not support certain devices.
