### ISSUE TITLE
Carriage return character

### ISSUE THREAD

**Issue by CaptainKludge** [naptha/tesseract.js#826]
Tesseract does not output carriage returns. After looking at an output file in a hex editor the reason is clear. Tesseract seems to determine line feeds prefectly fine but it only inserts the Line Feed character (0x0A) and not the carriage return character that a windows text file expects. (0x0D 0x0A)

So a better behavior would be to take 0x0D in an output string and replace the hex found with 0x0D 0x0A. Definitely increate usability.

**Comment by Balearica** [comment]
It sounds like you are taking issue with a behavior of Tesseract rather than any code in this repo.  Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to behaviors inherited from Tesseract--the goal is for Tesseract.js to behave identically to the main Tesseract project but in the browser.  Issues with how Tesseract works would need to be taken up in that project's repo. 

Additionally, I do not believe that switching from one OS-specific convention to another improves the package for all users.  While using the Windows-specific convention may be a mild convenience to Windows users, on Linux/Unix/iOS/Android the convention is `\n`.
