### ISSUE TITLE
Can't resolve 'encoding' in '......\node_modules\node-fetch\lib'

### ISSUE THREAD

**Issue by RaenonX** [naptha/tesseract.js#828]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**

**Describe the bug**
I keep getting this error using `next.js` v13.4.19
![image](https://github.com/naptha/tesseract.js/assets/18443743/753e6353-04da-4b8e-8108-cd7052c8f331)

Everything in `tesseract.js` works despite this warning.

According to https://stackoverflow.com/q/75438048/11571888, supabase/supabase-js#612 got this fixed. I am not using `supabase` unfortunately, so I still need to add `encoding` as dev dependency to remove the warning.

**To Reproduce**
1. Clone https://github.com/RaenonX/tesseract-js-error-repro
2. `npm install`
3. `npm dev`
4. Go to `localhost:3000`, or whatever shown in the console that invoked `localhost:3000`
5. Warnings are printed out in the console

**Expected behavior**
No warning in `next dev` output.

**Device Version:**
 - OS + Version: Windows 11
 - Node v18

**Additional context**
N/A

**Comment by Balearica** [comment]
Is this an issue on our end or with this particular framework?  The links you provided seem to indicate the latter. 

I can take a look at this, but I would need you to provide a repo + specific commands to run to reproduce as I am not familiar with this framework.

**Comment by RaenonX** [comment]
@Balearica Thanks for the response, updated my report

**Comment by Balearica** [comment]
Thanks for preparing the example repo.  I think this warning message is caused by some interaction between `node-fetch` and `Next.js`, and that fixing is outside of the scope of this project.  

The node-fetch package, including the latest version, handles the fact that `encoding` may or may not be installed by trying to import is within a `try` block.  Presumably Next.js is reporting this message to the console when the node-fetch developer did not intend this to be printed.  This does not occur using the Node.js examples in this repo. 

```
try {
	convert = require('encoding').convert;
} catch (e) {}

```
https://www.npmjs.com/package/node-fetch/v/2.7.0?activeTab=code

**Comment by RaenonX** [comment]
Oh, that's interesting to know. I'll try to file a next.js bug report. Is it OK if I leave this open for now?

**Comment by Balearica** [comment]
Sure, we can leave this issue open for now.

**Comment by RaenonX** [comment]
Can't tell why, but next `v13.5` is not showing this anymore, closing!
