### ISSUE TITLE
【BUG】cannot recognize the four directions texts for part symbol image

### ISSUE THREAD

**Issue by EasyEDA2021** [naptha/tesseract.js#861]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
v5.0.3
**Describe the bug**
as the image
![img_v3_026c_030a1028-ef46-4555-9838-c291aaf3670g](https://github.com/naptha/tesseract.js/assets/29702100/3b6b2a92-74f6-48e6-9663-063cd6b700cb)
for example, page 1
https://atta.szlcsc.com/upload/public/pdf/source/20151029/1457707509740.pdf

miss texts:
![image](https://github.com/naptha/tesseract.js/assets/29702100/8075071d-dff4-4776-a579-e7dd72eaf0e6)

**To Reproduce**
take the screeshot, and then import to Tesseract

Please attach any input image required to replicate this behavior.
![image](https://github.com/naptha/tesseract.js/assets/29702100/577c1ba4-5a8d-41b2-9f63-7e6ac0018c09)
![image](https://github.com/naptha/tesseract.js/assets/29702100/ae1ad35b-5029-49fb-87c8-0a60046b1472)
![image](https://github.com/naptha/tesseract.js/assets/29702100/1dd37a4c-9076-4c2c-a2c9-3a5ac25e57ad)

**Expected behavior**
support recognize four directions texts and correctly

**Device Version:**
 - OS + Version: [Windows 10]
 - Browser [Chrome 122]

**Additional context**
no

thank you for the nice job

**Comment by Balearica** [comment]
There are multiple intersecting reasons why these particular images perform poorly, however all are issues with the Tesseract OCR engine rather than Tesseract.js, so fixing would be outside of the scope of this repo. 

1. Tesseract is not capable of handling multiple text orientations within the same image
   - Tesseract should be capable of recognizing "this entire image needs to be rotated 90 degrees", however it is not capable of recognizing "this *word* needs to be rotated 90 degrees"
1. Tesseract often performs poorly when non-text elements are combined with text elements
   - Underlining text, drawing boxes around text, etc. often throws Tesseract off
1. Tesseract's often performs poorly when recognizing complex layouts
   - Any layout more complex than a basic 1 or 2 column layout, including images where text is essentially scattered throughout, is likely to perform poorly

For context, Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  Therefore, if you would like to pursue further, you should consult the documentation and discussion for the main Tesseract project.  You may find that there are configuration settings that may help to achieve better results.  

If you do not find settings that improve recognition, and believe this constitutes a (previously unreported) bug, then you should replicate the issue using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) program and raise the issue with that project.

**Comment by EasyEDA2021** [comment]
Hi Balearica
thank you for your reply, I got it, we will check this issue if Tesseract project met it
thanks
