### ISSUE TITLE
Got wrong result in Vietnamese language

### ISSUE THREAD

**Issue by sonht1109** [naptha/tesseract.js#869]
**Tesseract.js version** ^5.0.4

**Describe the bug**
I had tested ocr on one image which included Vietnamese text. Everything seemed okay but it still left one issue involving digits.

**To Reproduce**
My code
```
import { createWorker } from 'tesseract.js';

(async () => {
  const worker = await createWorker('vie');
  const ret = await worker.recognize('https://vov.vn/sites/default/files/inline-images/bai1sapo1.jpg');
  console.log(ret.data.text);
  await worker.terminate();
})();
```

Output:
![image](https://github.com/naptha/tesseract.js/assets/66255905/6393040c-e36b-45ae-a9ec-195e78b1c422)

**Expected behavior**
21/0/1973 => 21/9/1973

**Device Version:**
 - MacOS: 14.1
 - Node version: 18.19.0

**Comment by Balearica** [comment]
Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  If you would like to pursue further, you should (1) check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) and (2) if so, and you believe this constitutes a bug, raise the issue with that project.
