### ISSUE TITLE
Big text not recognised

### ISSUE THREAD

**Issue by IonicaBizau** [naptha/tesseract.js#871]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
5.0.4

**Describe the bug**
I have this image taken by DroidCam which I would like to analyze, but the big text is not identified correctly.

<img width="1361" alt="image" src="https://github.com/naptha/tesseract.js/assets/2864371/25313f69-4e3f-45f3-9b82-936e36338e0b">

**To Reproduce**
I uploaded the original image here.

**Expected behavior**
I would expect to identify the time and then the small text (amount of kW).

**Additional context**
I tried using `rectangle` to exclude the top side, but that didn't make a difference.

```js
const { createWorker } = require("tesseract.js");

const FRAME_URL = "frame.jpg";

(async () => {
  const worker = await createWorker('eng');
  const ret = await worker.recognize(FRAME_URL, {
      rectangle: {
          top: 11,
          left: 102,
          width: 481,
          height: 352
      },
  });
  console.log(ret.data.text);
  await worker.terminate();
})();
```

Original frame.jpg

![frame](https://github.com/naptha/tesseract.js/assets/2864371/213e2cf7-aa0b-4f01-95b2-5b76c7800b90)

**Comment by Balearica** [comment]
The fact that the boxes, which are supposed to be drawn around lines/words, have no relation to the word in your image indicates the issue is with the image processing step rather than recognition.  This can be confirmed by running the image processing example, which is linked [here](https://github.com/naptha/tesseract.js/blob/master/examples/browser/image-processing.html).

Below is the processed, binary image, which is what recognition is actually run on.
![download (22)](https://github.com/naptha/tesseract.js/assets/100809261/1afbd10c-0669-4dcf-a8f5-51b36455877f)

Your instinct that this can be resolved by cropping the image appears to be correct--cropping to only include the text results in the time `11:39` being properly identified.  It is easy to see why when looking at the binarized image, which is below. 

![display_image_crop1](https://github.com/naptha/tesseract.js/assets/100809261/bf417837-5c02-4d2b-aa7a-0927da767b68)
![download (26)](https://github.com/naptha/tesseract.js/assets/100809261/45896975-01fd-4446-b596-8a8a475365df)

The reason why setting `rectangle` did not produce these results is because this argument does not impact image processing.  That argument merely tells Tesseract to only run recognition on a specific region.    Therefore, to fix issues with image processing by cropping, you would need to crop the image prior to passing it to Tesseract.js.

**Comment by IonicaBizau** [comment]
Thank you very much! I used `sharp` to modify the image before passing it to tesseract and I got better results. Thanks for this amazing library!

**Comment by IonicaBizau** [comment]
@Balearica I am wondering why such an image (attached below) cannot be processed... There is no text at all coming in the response. Do you have any ideas?

![current-power](https://github.com/naptha/tesseract.js/assets/2864371/cf032466-9718-41d0-930d-db612ccc6e2d)
