### ISSUE TITLE
A lot of garbage instead of dots (...)

### ISSUE THREAD

**Issue by 0xff00ff** [naptha/tesseract.js#873]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
^5.0.4

**Describe the bug**
I try to recognize a text with a lot of dots, and some times it adds instead  (and sometimes after those dots some garbage of random letters.

**To Reproduce**
I use this code:
```
const { createWorker } = require('tesseract.js');

(async () => {
  const worker = await createWorker("pol", 1, {
    logger: m => console.log(m),
  });
  const { data: { text } } = await worker.recognize("https://0x-tesseract.s3.amazonaws.com/Screenshot+2024-01-15+000829.png");
  console.log(text);
  await worker.terminate();
})();
```

**Expected behavior**

**Device Version:**
 - OS + Version: windows 11 + wsl2
 - Node v18

source image:
<img width="610" alt="Screenshot 2024-01-15 000829" src="https://github.com/naptha/tesseract.js/assets/669518/e6969d85-51d8-4ac6-87fc-b988ef9a66b4">

The resylt looks like:
```Zakupy Mami | NRL

W koszyku z „zakupami. (zakupy) Są ........eeenenoeneneenenene dzezzronoenonownenowneneeeee (OWOC, warzywo). Są tam
awanawnananowawnowowawnanew | eaenonawnanowawaenenawoenene | sesesaeneseeeeneseseeeeeee (dojrzały czerwony pomidor — I. mn.), — siesaroononoononowoononene
aśdzswśonisrwsawiośwwianeśs (ZfeloNy, Ogórek — /..mN;)  ... <cutted>

**Comment by Balearica** [comment]
I believe what you are describing is a limitation of the Tesseract recognition model(s) rather than something specific to Tesseract.js.  Tesseract.js is the Javascript/Webassembly port of Tesseract, so making changes to the model is outside of the scope of this repo. 

From personal experience, I can confirm that the LSTM model (`oem` value `1`) is prone to hallucinating text given dots or squiggles.  The Legacy model (`oem` value `0`) will be less prone to hallucinating words that are completely at odds with what you see on the page, as it relies more on the shape of the individual letters, so you could try using that.  However, in addition to being less accurate in general, the Legacy model is known to struggle with italics, which your image contains.  Therefore, I would not expect either model to give excellent results for your image without pre or post processing to filter off the junk. 

Tesseract offers many different configuration settings that you can experiment with, so it is possible that there is some setting that would help in this case.  These options would be documented in the main [Tesseract documentation](https://tesseract-ocr.github.io/tessdoc/) or [repo](https://github.com/tesseract-ocr/tesseract), rather than here in the Tesseract.js repo.  Every configuration setting for Tesseract can also be used in Tesseract.js.
