### ISSUE TITLE
Its possible to use  user_patterns_file or user_patterns_suffix ?

### ISSUE THREAD

**Issue by bruno-castilho** [naptha/tesseract.js#880]
How i can to use user_patterns_file or user_patterns_suffix ?

I try:

```
const worker = await createWorker('por');
worker.setParameters({ 
  tessedit_char_whitelist: '0123456789', 
  user_patterns_suffix: /(\d+)(\d+)(\d+)(\d+)(\d+)(\d+)/
})
```

OR

```
const worker = await createWorker('por');
worker.setParameters({ 
  tessedit_char_whitelist: '0123456789', 
  user_patterns_file: mypaterns_file
})
```

but not working for me, how i can do it ?

**Comment by Balearica** [comment]
It should be possible to use all Tesseract arguments with Tesseract.js, however we do not document most of the arguments here.  I would start by reviewing the Tesseract documentation, and getting this working with [Tesseract](https://github.com/tesseract-ocr/tesseract).  Then, once you have a working example with Tesseract, start thinking about how to make it work with Tesseract.js. 

I have not used these arguments before so cannot comment much on your usage.  However, I will note that all "file" arguments refer to the virtual file system used by Tesseract.js rather than the file system on your local computer or web server.  Therefore, if `mypaterns_file` does not exist on the virtual file system then setting `user_patterns_file: mypaterns_file` will not work.  You can write files to the virtual file system using the `writeFile` function.

**Comment by Balearica** [comment]
An working example implementing `user_patterns_file` can be found in [this comment](https://github.com/naptha/tesseract.js/issues/492#issuecomment-2067514102).
