### ISSUE TITLE
Suppressing "Corrupt JPEG data: 1 extraneous bytes before marker 0xd9" output

### ISSUE THREAD

**Issue by matthieuEv** [naptha/tesseract.js#929]
**Tesseract.js version 5.1.0**

Hello,

I am using Tesseract.js for a project and have encountered an issue where the library outputs the following message to the console:
```sh
Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
```

While I understand that this message indicates a problem with the JPEG data, it is not something that affects the functioning of my application. However, the frequent appearance of this message in the console clutter the output and make it difficult to debug other issues.

I would like to know if there is a way to suppress this specific output from being logged to the console. I have attempted to use custom logger functions, but the message still appears. Temporarily overriding console.log, console.warn, and console.error works, but it feels like a hack rather than a solution.

**Steps to Reproduce:**

- Use Tesseract.js to recognize text from a JPEG image.
- Ensure the image has minor corruption that triggers the "Corrupt JPEG data" warning.
- Observe the console output.

**Expected Behavior:**
There should be an option to disable or suppress specific log messages, such as the "Corrupt JPEG data" warning.

**Actual Behavior:**
The message is printed to the console regardless of custom logger settings or other configurations.

**Request:**
Could you please provide a way to suppress this specific log message, or guide me on how to properly handle it without resorting to overriding global console methods?

Thank you for your assistance!

**Comment by ImSpyke** [comment]
I am working on this project too, dont hesitate to ping me too ^^

**Comment by matthieuEv** [comment]
Any news? :)

**Comment by Balearica** [comment]
Please provide an example image that can be used to replicate this issue.

**Comment by Balearica** [comment]
> I would like to know if there is a way to suppress this specific output from being logged to the console. I have attempted to use custom logger functions, but the message still appears. Temporarily overriding console.log, console.warn, and console.error works, but it feels like a hack rather than a solution.

Since these warning messages are created by Tesseract rather than being something added by Tesseract.js, disabling specific warning messages at the source is outside of the scope of this repo.  Indeed, the only way filter messages Tesseract prints to `stderr` without modifying the Tesseract codebase would be to implement the hacky solutions you describe (e.g. overriding `console.log`).  

However, Tesseract does support saving warning messages as an output, rather than printing them to `stderr` (which maps to `console.warn` in JavaScript).  Therefore, by redirecting the messages to the output, you should be able to implement something similar to what you are describing.  To capture debugging messages in the output object, rather than printing them to console, set the `debug` to `true` within the output options.  

```js
const worker = await await Tesseract.createWorker("eng");
const ret = await worker.recognize(files[i], undefined, {debug: true});
console.log(ret.data.text);
console.log(`Captured message: ${ret.data.debug}`);
```

```
Captured message: Estimating resolution as 390
```

Once you have the debug output string, you can either ignore it or save it to a string--essentially suppressing all warning messages from the console--or write a wrapper function that prints warnings only when they meet certain criteria.

**Comment by matthieuEv** [comment]
Hello, sorry for my inactivity here😅, this method seems to work for me, thanks again 😁
