### ISSUE TITLE
Unable to use setParameters for user_defined_dpi

### ISSUE THREAD

**Issue by EffDuBois** [naptha/tesseract.js#966]
**Tesseract.js version 5.1.1**

**Describe the bug**
The worker.setParams() function is not setting the config as expected

**To Reproduce**
1. Create a worker using createWorker           // createWorker("eng", 2)
2. try to setParams using worker.setParams() //  worker.setParameters({ user_defined_dpi: "300" })
3. Give an image to test                                 // eg- an image with no metadata
4. 
![image](https://github.com/user-attachments/assets/d9cbe6ff-548e-43e6-9f07-0a01d72ea860)

this is the code snippet

```js
export default async function getTextFromImg(image: string) {
  const worker = await createWorker("eng", 2, {
    legacyLang: true,
  });
  worker.setParameters({ user_defined_dpi: "300" });

  const ocrData = await worker.recognize(
   image,
    {},
    { text: true }
  );
  console.log(ocrData);
  worker.terminate();
  return ocrData.data.text;
}
```

**Expected behavior**
On missing dpi, tesseract should fall back to 300 dpi instead of the default 70 dpi

**Device Version:**
 - OS + Version: Windows 11 23H2
 -  edge || node v20.17.0

**Comment by Balearica** [comment]
Please update to include a reproducible example snippet that can be run as written to reproduce the issue (without needing to write code or source an affected image). 

Additionally, please update the title so this issue is searchable by other users encountering similar problems.  There is no `setParams` function, and the `setParameters` function is definitely not broken across the board.  An appropriate title might be "Unable to use `setParameters` to set resolution using `user_defined_dpi`".

**Comment by EffDuBois** [comment]
@Balearica it was the detect feature throwing the error, Thank you for your time, appreciate the work you do here!
